### ISSUE TITLE
trainers.c Is not properly randomizing trainers.

### ISSUE THREAD

**Issue by vermillion-excl** [XLuma/BDSP_Randomizers_Public#2]
Executing the trainer randomizer will only shift a handful of values called P1FormNo and P2FormNo around.

Issue was originally brought up in this tweet: https://twitter.com/Accuhorsemat/status/1463236142166208513

I was able to verify this on my end as well. No errors are outputted during the randomization.

EDIT: Original folder structure is preserved, all programs are inside /Randomizers.

**Comment by XLuma** [comment]
Not all trainers have 6 pokemons. I am verifying for any value equal to 0, so if you are only checking the first trainers you may see obviously, only P1 and P2. 
I will still verify if such an issue arises.

**Comment by XLuma** [comment]
I can confirm there is a bug with the trainer randomizer. Fixing.

**Comment by vermillion-excl** [comment]
Amazing, thank you.

**Comment by XLuma** [comment]
Bug has been fixed. I was searching for the wrong string for MonsNo values, and was allocating too little memory when randomizing moves. Both issues have now been resolved, and trainer randomizer is confirmed working.

**Comment by vermillion-excl** [comment]
I'm still experiencing this issue on the latest commit. @XLuma 

Included image of the git view. https://i.imgur.com/zhFpHUc.png

EDIT: The "Randomizing..." stage only runs for about 5 seconds before it completes.

**Comment by XLuma** [comment]
Please use the more recent changes. Make sure you are using linux paths, not windows.
